ARG FROM_TAG="latest"
FROM pulp/base-cs10:${FROM_TAG}
# https://ryandaniels.ca/blog/docker-dockerfile-arg-from-arg-trouble/

RUN curl -Ls "https://github.com/just-containers/s6-overlay/releases/download/v3.1.6.2/s6-overlay-$(arch).tar.xz" | tar xvJ -C /
RUN curl -Ls https://github.com/just-containers/s6-overlay/releases/download/v3.1.6.2/s6-overlay-noarch.tar.xz | tar xvJ -C /
RUN curl -Ls https://github.com/just-containers/s6-overlay/releases/download/v3.1.6.2/s6-overlay-symlinks-noarch.tar.xz | tar xvJ -C /
RUN curl -Ls https://github.com/just-containers/s6-overlay/releases/download/v3.1.6.2/s6-overlay-symlinks-arch.tar.xz | tar xvJ -C /

ENV PULP_GUNICORN_RELOAD=${PULP_GUNICORN_RELOAD:-false}

ENV PULP_WORKERS=2

ENV PULP_HTTPS=false

ENV PULP_STATIC_ROOT=/var/lib/operator/static/

ENV S6_BEHAVIOUR_IF_STAGE2_FAILS=1
# Needed because otherwise all services must start within 5 seconds
# https://github.com/just-containers/s6-overlay/issues/467
ENV S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0

RUN dnf -y install "https://download.postgresql.org/pub/repos/yum/reporpms/EL-10-$(arch)/pgdg-redhat-repo-latest.noarch.rpm" && \
    dnf -y install postgresql16 \
      postgresql16-server \
      postgresql16-contrib \
      nginx \
      valkey && \
    dnf clean all

# Valkey compatibility: s6 service scripts expect redis-server, redis user, and /etc/redis/redis.conf
# Also create runtime directories that tmpfiles.d would normally handle via systemd
RUN ln -s /usr/bin/valkey-server /usr/bin/redis-server && \
    ln -s /etc/valkey /etc/redis && \
    ln -s /etc/valkey/valkey.conf /etc/valkey/redis.conf && \
    useradd -o -u $(id -u valkey) -g $(id -g valkey) -M -N redis || true && \
    install -d -m 0755 -o valkey -g valkey /run/valkey && \
    install -d -m 0750 -o valkey -g valkey /var/log/valkey && \
    # Valkey defaults to writing dump files to ./ which fails if cwd is not writable
    install -d -m 0750 -o valkey -g valkey /var/lib/valkey && \
    sed -i 's|^[# ]*dir .*|dir /var/lib/valkey|' /etc/valkey/valkey.conf

RUN alternatives --install /usr/bin/postgres postgres /usr/pgsql-16/bin/postgres 160 \
      --follower /usr/bin/pg_dump pg_dump /usr/pgsql-16/bin/pg_dump \
      --follower /usr/bin/pg_dumpall pg_dumpall /usr/pgsql-16/bin/pg_dumpall \
      --follower /usr/bin/pg_restore pg_restore /usr/pgsql-16/bin/pg_restore \
      --follower /usr/bin/psql psql /usr/pgsql-16/bin/psql \
      --follower /usr/bin/createdb createdb /usr/pgsql-16/bin/createdb \
      --follower /usr/bin/dropdb dropdb /usr/pgsql-16/bin/dropdb \
      --follower /usr/bin/createuser createuser /usr/pgsql-16/bin/createuser \
      --follower /usr/bin/dropuser dropuser /usr/pgsql-16/bin/dropuser \
      --follower /usr/bin/pg_isready pg_isready /usr/pgsql-16/bin/pg_isready \
      --follower /usr/bin/pg_basebackup pg_basebackup /usr/pgsql-16/bin/pg_basebackup \
      --follower /usr/bin/pg_ctl pg_ctl /usr/pgsql-16/bin/pg_ctl \
      --follower /usr/bin/initdb initdb /usr/pgsql-16/bin/initdb \
      --follower /usr/bin/pg_upgrade pg_upgrade /usr/pgsql-16/bin/pg_upgrade

COPY images/s6_assets/openssl.cnf /etc/ssl/pulp/openssl.cnf
COPY images/s6_assets/v3.cnf /etc/ssl/pulp/v3.cnf
COPY images/s6_assets/wait_on_database_migrations.sh /database/assets/wait_on_database_migrations.sh
COPY images/s6_assets/template_nginx.py /nginx/template_nginx.py
COPY images/s6_assets/nginx.conf.j2 /nginx/nginx.conf.j2
COPY images/s6_assets/s6-rc.d /etc/s6-overlay/s6-rc.d
COPY images/s6_assets/init /etc/init
COPY images/s6_assets/fix-attrs.d /etc/fix-attrs.d

CMD ["/init"]

EXPOSE 80
