FROM pulp/pulp-ci:latest

ARG PULPCORE_VERSION=3.4.1
ARG PULP_FILE_VERSION=1.0.1
ARG PULP_CONTAINER_VERSION=2.0.0b2
ARG PULP_ANSIBLE_VERSION=0.2.0b13
ARG PULP_RPM_VERSION=3.4.1
ARG PULP_MAVEN_VERSION=0.1.0

RUN pip3 install --upgrade \
  requests \
  pulpcore==${PULPCORE_VERSION} \
  pulp-file==${PULP_FILE_VERSION} \
  pulp-container==${PULP_CONTAINER_VERSION} \
  pulp-ansible==${PULP_ANSIBLE_VERSION} \
  pulp-rpm==${PULP_RPM_VERSION} \
  pulp-maven==${PULP_MAVEN_VERSION}

RUN ln /usr/local/lib/python3.7/site-packages/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf
RUN ln /usr/local/lib/python3.7/site-packages/pulp_container/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_container.conf
