FROM pulp/base:latest

RUN pip3 install pulpcore \
  pulp_ansible \
  pulp-certguard \
  pulp_container \
  pulp_deb \
  pulp_file \
  pulp_maven \
  pulp_python \
  pulp_rpm

USER pulp:pulp
RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
       /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
USER root:root
