---
name: Build Base Images
description: Build the base images (pulp/base & pulp/pulp-ci-centos9) if needed
# Use hashFiles(base_image_files, pulp-ci_image_files) for rebuild check
inputs:
  image_variants:
    description: "Whether build is nightly or stable, nightly never rebuilds"
    default: "stable"
    required: true
outputs:
  rebuilt_images:
    value: ${{ steps.rebuild_needed.outputs.build }}
    description: "true/false if the base images were rebuilt"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Calculate base images hash
      run: |
        hash=${{ hashFiles('images/Containerfile.core.base', 'images/pulp_ci_centos/Containerfile', 'images/assets/**', 'images/s6_assets/**') }}
        echo "base image hash is ${hash}"
        echo "HASH=${hash}" >> $GITHUB_ENV
      shell: bash

    - name: Set up oras
      uses: oras-project/setup-oras@v1

    - name: Check for updates on base images
      id: rebuild_needed
      run: |
        if [[ "${{ inputs.image_variants }}" == "nightly" ]]; then
          build=false
        else
          branch=${{ github.base_ref || github.ref_name }}
          config=$(oras manifest fetch-config --platform linux/amd64 ghcr.io/pulp/pulp-ci-centos9:${branch} | jq -r '.config.Labels')
          latest_hash=$(echo "${config}" | jq -r '."org.pulp.basefiles-hash"')
          build=true
          echo "Checking hash for ${branch}: ${latest_hash}"
          if [[ "${latest_hash}" == "${HASH}" ]]; then
            if podman run ghcr.io/pulp/pulp-ci-centos9:${branch} bash -c "dnf check-upgrade"; then
              echo "No base images rebuild needed :)"
              build=false
            fi
          fi
        fi
        echo "build=${build}" >> "$GITHUB_OUTPUT"
        echo "Going to rebuild: ${build}"
      shell: bash

    - name: Download base images if no rebuild needed
      if: steps.rebuild_needed.outputs.build == 'false'
      run: |
        echo "Downloading base images"
        branch=${{ github.base_ref || github.ref_name }}
        podman pull ghcr.io/pulp/base:${branch}
        podman pull ghcr.io/pulp/pulp-ci-centos9:${branch}
        podman tag ghcr.io/pulp/base:${branch} pulp/base:ci
        podman tag ghcr.io/pulp/pulp-ci-centos9:${branch} pulp/pulp-ci-centos9:ci
      shell: bash

    - name: Build images
      if: steps.rebuild_needed.outputs.build == 'true'
      run: |
        podman version
        buildah version
        podman build --format docker --file images/Containerfile.core.base --tag "pulp/base:ci" --label "org.pulp.basefiles-hash=${HASH}" .
        podman build --format docker --file images/pulp_ci_centos/Containerfile --tag "pulp/pulp-ci-centos9:ci" --build-arg FROM_TAG="ci" .
      shell: bash
