FROM pulp/base:latest

RUN pip3 install git+https://github.com/pulp/pulpcore.git#egg=pulpcore \
  git+https://github.com/pulp/pulp_ansible.git \
  git+https://github.com/pulp/pulp-certguard.git \
  git+https://github.com/pulp/pulp_container.git \
  git+https://github.com/pulp/pulp_cookbook.git \
  git+https://github.com/pulp/pulp_deb.git \
  git+https://github.com/pulp/pulp_file.git \
  git+https://github.com/pulp/pulp_gem.git \
  git+https://github.com/pulp/pulp_maven.git \
  git+https://github.com/pulp/pulp_npm.git \
  git+https://github.com/pulp/pulp_ostree.git \
  git+https://github.com/pulp/pulp_python.git \
  git+https://github.com/pulp/pulp_rpm.git

USER pulp:pulp
RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
       /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
USER root:root
