ARG FROM_TAG="latest"
FROM pulp/base:${FROM_TAG}

COPY images/assets/requirements.extra.txt /requirements.extra.txt
COPY images/assets/requirements.minimal.txt /requirements.minimal.txt

RUN pip3 install \
  pulpcore[s3,google,azure]@git+https://github.com/pulp/pulpcore.git \
  git+https://github.com/pulp/pulp_ansible.git \
  git+https://github.com/pulp/pulp_container.git \
  git+https://github.com/pulp/pulp_deb.git \
  git+https://github.com/pulp/pulp_gem.git \
  git+https://github.com/pulp/pulp_maven.git \
  git+https://github.com/pulp/pulp_ostree.git \
  git+https://github.com/pulp/pulp_python.git \
  git+https://github.com/pulp/pulp_rpm.git \
  -r /requirements.extra.txt \
  -r /requirements.minimal.txt \
  -c /constraints.txt && \
  rm -rf /root/.cache/pip

USER pulp:pulp
RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
       /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
USER root:root

RUN chmod 2775 /var/lib/pulp/{scripts,media,tmp,assets}
RUN chown :root /var/lib/pulp/{scripts,media,tmp,assets}
