ARG FROM_TAG="nightly"
FROM pulp/pulp-minimal:${FROM_TAG} as builder

RUN mkdir -p /etc/nginx/pulp \
             /www/data \
  && ln $(pip show pulp_ansible | sed -n -e 's/Location: //p')/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf \
  && ln $(pip show pulp_container | sed -n -e 's/Location: //p')/pulp_container/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_container.conf \
  && ln $(pip show pulp_python | sed -n -e 's/Location: //p')/pulp_python/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_python.conf


FROM docker.io/nginx:latest

RUN mkdir -p /etc/nginx/pulp
COPY --from=builder /etc/nginx/pulp/*.conf /etc/nginx/pulp

RUN chmod 775 /var/cache/nginx /var/run

# Run script uses standard ways to run the application
CMD nginx -g "daemon off;"
