version: '3'
services:
  postgres:
    image: "docker.io/library/postgres:13"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pulp
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
      POSTGRES_DB: pulp
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: 'scram-sha-256'
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    secrets:
      - db_password
    restart: always
    healthcheck:
      test: pg_isready -U pulp
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: "docker.io/library/redis:latest"
    volumes:
      - "redis_data:/data"
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5

  migration_service:
    image: "pulp/pulp-minimal:latest"
    depends_on:
      postgres:
        condition: service_healthy
    command: pulpcore-manager migrate --noinput
    volumes:
      - "./assets/settings.py:/etc/pulp/settings.py:z"
      - "pulp:/var/lib/pulp"
    secrets:
      - app_secret
      - db_password
      - db_encryption_key

  signing_key_service:
    image: "pulp/pulp-minimal:latest"
    command: sh -c "add_signing_service.sh"
    depends_on:
      postgres:
        condition: service_healthy
      migration_service:
        condition: service_completed_successfully
    volumes:
      - "./assets/settings.py:/etc/pulp/settings.py:z"
      - "pulp:/var/lib/pulp"
    secrets:
      - app_secret
      - db_password
      - db_encryption_key

  set_init_password_service:
    image: "pulp/pulp-minimal:latest"
    command: set_init_password.sh
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PULP_DEFAULT_ADMIN_PASSWORD: password
    volumes:
      - "./assets/settings.py:/etc/pulp/settings.py:z"
      - "pulp:/var/lib/pulp"
    secrets:
      - app_secret
      - db_password
      - db_encryption_key

  pulp_web:
    image: "pulp/pulp-web:latest"
    command: ['/usr/bin/nginx.sh']
    depends_on:
      pulp_api:
        condition: service_healthy
      pulp_content:
        condition: service_healthy
    ports:
      - "8080:8080"
    hostname: pulp
    user: root
    volumes:
      - "./assets/bin/nginx.sh:/usr/bin/nginx.sh:Z"
      - "./assets/nginx/nginx.conf.template:/etc/opt/rh/rh-nginx116/nginx/nginx.conf.template:Z"
    restart: always

  pulp_api:
    image: "pulp/pulp-minimal:latest"
    deploy:
      replicas: 2
    command: ['pulp-api']
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migration_service:
        condition: service_completed_successfully
      set_init_password_service:
        condition: service_completed_successfully
      signing_key_service:
        condition: service_completed_successfully
    hostname: pulp-api
    user: pulp
    volumes:
      - "./assets/settings.py:/etc/pulp/settings.py:z"
      - "pulp:/var/lib/pulp"
    secrets:
      - app_secret
      - db_password
      - db_encryption_key
    restart: always
    healthcheck:
      test: readyz.py /pulp/api/v3/status/
      interval: 10s
      timeout: 5s
      retries: 5

  pulp_content:
    image: "pulp/pulp-minimal:latest"
    deploy:
      replicas: 2
    command: ['pulp-content']
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migration_service:
        condition: service_completed_successfully
    hostname: pulp-content
    user: pulp
    volumes:
      - "./assets/settings.py:/etc/pulp/settings.py:z"
      - "pulp:/var/lib/pulp"
    secrets:
      - app_secret
      - db_password
      - db_encryption_key
    restart: always
    healthcheck:
      test: readyz.py /pulp/content/
      interval: 10s
      timeout: 5s
      retries: 5

  pulp_worker:
    image: "pulp/pulp-minimal:latest"
    deploy:
        replicas: 2
    command: ['pulp-worker']
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      migration_service:
        condition: service_completed_successfully
    user: pulp
    volumes:
      - "./assets/settings.py:/etc/pulp/settings.py:z"
      - "pulp:/var/lib/pulp"
    secrets:
      - app_secret
      - db_password
      - db_encryption_key
    restart: always

secrets:
  app_secret:
    file: ./assets/app_secret.txt
  db_password:
    file: ./assets/db_password.txt
  db_encryption_key:
    file: ./assets/db_encryption_key.txt

volumes:
  pulp:
    name: pulp${DEV_VOLUME_SUFFIX:-dev}
  pg_data:
    name: pg_data${DEV_VOLUME_SUFFIX:-dev}
  redis_data:
    name: redis_data${DEV_VOLUME_SUFFIX:-dev}
