#!/usr/bin/bash

export BASENAME=$(basename ${0})
export PREFIX="[oneshot] ${BASENAME}:"

export ENDCOLOR="\e[0m"
export BLACK="\e[30m"
export RED="\e[31m"
export GREEN="\e[32m"
export ORANGE="\e[33m"
export C034="\e[34m"
export C035="\e[35m"
export C036="\e[36m"
export C037="\e[37m"

if ! [ -d /etc/pulp/certs ]; then
  mkdir -p /etc/pulp/certs
fi

echo -e "${PREFIX} ${GREEN}creating database fields key${ENDCOLOR}"
if ! [ -e /etc/pulp/certs/database_fields.symmetric.key ]; then
  openssl rand -base64 32 > /etc/pulp/certs/database_fields.symmetric.key
  chmod 640 /etc/pulp/certs/database_fields.symmetric.key
  chown root:pulp /etc/pulp/certs/database_fields.symmetric.key
fi
