#!/bin/bash

# Fix permissions on /var/lib/pulp
# We do not want to always fix permissions on it at every boot because it would
# take very long. So we check individual subdirs.

set -eu

export BASENAME=$(basename ${0})
export PREFIX="[oneshot] ${BASENAME}:"

export ENDCOLOR="\e[0m"
export BLACK="\e[30m"
export RED="\e[31m"
export GREEN="\e[32m"
export ORANGE="\e[33m"
export C034="\e[34m"
export C035="\e[35m"
export C036="\e[36m"
export C037="\e[37m"

HOME_DIR=/var/lib/pulp
DIRECTORIES_NEEDED=(media scripts tmp)

owner="$(stat --format '%U' $HOME_DIR)"
if [ "$owner" != "pulp" ]; then
  echo -e "${PREFIX} ${GREEN}chown pulp:pulp $HOME_DIR${ENDCOLOR}"
  chown pulp:pulp $HOME_DIR
fi

for dir in "${DIRECTORIES_NEEDED[@]}"; do
  DIRECTORY_NEEDED=$HOME_DIR/$dir
  if [ ! -d $DIRECTORY_NEEDED ]; then
    echo "Creating directory $DIRECTORY_NEEDED"
    mkdir -p $DIRECTORY_NEEDED
  fi;

  echo "Checking $DIRECTORY_NEEDED permissions"
  owner="$(stat --format '%U' $DIRECTORY_NEEDED)"

  if [ "$owner" != "pulp" ]; then
    echo -e "${PREFIX} ${GREEN}chown -R pulp:pulp $DIRECTORY_NEEDED${ENDCOLOR}"
    chown -R pulp:pulp $DIRECTORY_NEEDED
  fi

done
