#!/bin/bash
if [ "${PULP_GUNICORN_RELOAD}" = "true" ]; then
  PULP_GUNICORN_RELOAD_STRING="--reload"
fi
exec /usr/local/bin/gunicorn pulpcore.content:server --bind "127.0.0.1:24816" --name pulp-content --timeout "${PULP_GUNICORN_TIMEOUT}" --worker-class "aiohttp.GunicornWebWorker" --workers "${PULP_CONTENT_WORKERS}" --access-logfile - ${PULP_GUNICORN_RELOAD_STRING}
