#!/bin/bash
if [ "${PULP_GUNICORN_RELOAD}" = "true" ]; then
  PULP_GUNICORN_RELOAD_STRING="--reload"
fi
if [ "${PULP_OTEL_ENABLED}" = "true" ]; then
  OTEL_PREFIX="/usr/local/bin/opentelemetry-instrument --service_name pulp-content"
fi

if which pulpcore-content
then
  PULP_CONTENT_ENTRYPOINT=("pulpcore-content")
else
  PULP_CONTENT_ENTRYPOINT=("gunicorn" "pulpcore.content:server" "--worker-class" "aiohttp.GunicornWebWorker" "--name" "pulp-content" "--bind" "127.0.0.1:24816")
fi

exec ${OTEL_PREFIX} "${PULP_CONTENT_ENTRYPOINT[@]}" \
  --timeout "${PULP_GUNICORN_TIMEOUT}" \
  --workers "${PULP_CONTENT_WORKERS}" \
  --access-logfile - \
  ${PULP_GUNICORN_RELOAD_STRING}
