#!/bin/bash
if [ "${PULP_GUNICORN_RELOAD}" = "true" ]; then
  PULP_GUNICORN_RELOAD_STRING="--reload"
fi
if [ "${PULP_OTEL_ENABLED}" = "true" ]; then
  OTEL_PREFIX="/usr/local/bin/opentelemetry-instrument --service_name pulp-api"
fi

if which pulpcore-api
then
  PULP_API_ENTRYPOINT=("pulpcore-api")
else
  PULP_API_ENTRYPOINT=("gunicorn" "pulpcore.app.wsgi:application" "--bind" "127.0.0.1:24817" "--name" "pulp-api" "--access-logformat" "pulp [%({correlation-id}o)s]: %(h)s %(l)s %(u)s %(t)s \"%(r)s\" %(s)s %(b)s \"%(f)s\" \"%(a)s\"")
fi

# Process recycling only supported for pulpcore >= 3.41.0
# due to https://github.com/pulp/pulpcore/issues/4679
if python3 -c \
  'import importlib.metadata; \
   from packaging.version import Version; \
   exit(\
    int(\
      not(\
        Version(\
          importlib.metadata.version("pulpcore")\
        ) >= \
        Version("3.41.0")\
      )\
    )\
  )'
then
  PULP_GUNICORN_PROCESS_RECYCLING_STRING="--max-requests ${PULP_API_WORKERS_MAX_REQUESTS} --max-requests-jitter ${PULP_API_WORKERS_MAX_REQUESTS_JITTER}"
fi

exec ${OTEL_PREFIX} "${PULP_API_ENTRYPOINT[@]}" \
  --timeout "${PULP_GUNICORN_TIMEOUT}" \
  --workers "${PULP_API_WORKERS}" \
  ${PULP_GUNICORN_PROCESS_RECYCLING_STRING} \
  --access-logfile - \
  ${PULP_GUNICORN_RELOAD_STRING}
