FROM quay.io/pulp/base:3.21

RUN pip install pulpcore~=3.21.0 \
  pulp_ansible \
  pulp-certguard \
  pulp_container \
  pulp_deb \
  pulp_file \
  pulp_python \
  pulp_rpm

USER pulp:pulp
RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
  /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
USER root:root

RUN chmod 2775 /var/lib/pulp/{scripts,media,tmp,assets}
RUN chown :root /var/lib/pulp/{scripts,media,tmp,assets}
