ARG FROM_TAG="latest"
FROM pulp/pulp-ci-centos9:${FROM_TAG}

ARG PULPCORE_VERSION=""
ARG PULP_ANSIBLE_VERSION=""
ARG PULP_CERTGUARD_VERSION=""
ARG PULP_CONTAINER_VERSION=""
ARG PULP_DEB_VERSION=""
ARG PULP_FILE_VERSION=""
ARG PULP_GEM_VERSION=""
ARG PULP_MAVEN_VERSION=""
ARG PULP_PYTHON_VERSION=""
ARG PULP_RPM_VERSION=""
ARG PULP_OSTREE_VERSION=""
ARG PULP_UI_URL=""

ENV PULP_UI=true
COPY images/assets/requirements.extra.txt /requirements.extra.txt

RUN pip3 install --upgrade \
  pulpcore[s3,google,azure]${PULPCORE_VERSION} \
  pulp-ansible${PULP_ANSIBLE_VERSION} \
  pulp-certguard${PULP_CERTGUARD_VERSION} \
  pulp-container${PULP_CONTAINER_VERSION} \
  pulp-deb${PULP_DEB_VERSION} \
  pulp-file${PULP_FILE_VERSION} \
  pulp-gem${PULP_GEM_VERSION} \
  pulp-maven${PULP_MAVEN_VERSION} \
  pulp-python${PULP_PYTHON_VERSION} \
  pulp-rpm${PULP_RPM_VERSION} \
  pulp-ostree${PULP_OSTREE_VERSION} \
  -r /requirements.extra.txt \
  -c /constraints.txt && \
  rm -rf /root/.cache/pip

USER pulp:pulp
RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
       /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
USER root:root

RUN ln $(pip3 show pulp_ansible | sed -n -e 's/Location: //p')/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf
RUN ln $(pip3 show pulp_container | sed -n -e 's/Location: //p')/pulp_container/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_container.conf
RUN ln $(pip3 show pulp_python | sed -n -e 's/Location: //p')/pulp_python/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_python.conf

RUN <<EOF
if [[ "$PULP_UI_URL" ]]; then
    mkdir -p /usr/share/nginx/static/pulp_ui
    curl -Ls $PULP_UI_URL | tar -xzv -C /usr/share/nginx/static/pulp_ui
fi
EOF
