#!/usr/bin/bash

export BASENAME=$(basename ${0})
export PREFIX="[oneshot] ${BASENAME}:"

export ENDCOLOR="\e[0m"
export BLACK="\e[30m"
export RED="\e[31m"
export GREEN="\e[32m"
export ORANGE="\e[33m"
export C034="\e[34m"
export C035="\e[35m"
export C036="\e[36m"
export C037="\e[37m"

PGVERSION=$(postgres --version | egrep -o "1[0-9]")
PGHOME="/var/lib/pgsql"
PGDATA="${PGHOME}/data"
PGDATA_OLD="${PGHOME}/data_old"
PGDATA_OLD_RENAMED="${PGHOME}/data_old.$(date --rfc-3339=seconds)"

if [ -d "${PGDATA}/base" -a -f "${PGDATA}/PG_VERSION" ]; then
  PGDATA_VERSION=$(cat "${PGDATA}/PG_VERSION")
  if [ "${PGDATA_VERSION}" != "${PGVERSION}" ]; then
    echo -e "${PREFIX} ${ORANGE} Postgresql database exists but will be upgraded from ${PGDATA_VERSION} to ${PGVERSION}${ENDCOLOR}"
    if [ -d ${PG_DATA_OLD} ]; then
      echo -e "${PREFIX} ${ORANGE} Renaming ${PGDATA_OLD} ${PGDATA_OLD} to ${PGDATA_OLD_RENAMED}${ENDCOLOR}"
      mv ${PGDATA_OLD} "${PGDATA_OLD_RENAMED}"
    fi
    su postgres -c "PGSETUP_INITDB_OPTIONS=\"-E UTF8 --auth=trust\" postgresql-upgrade ${PGDATA}" || { echo -e "${PREFIX} ${RED} Failed to upgrade the postgresql database${ENDCOLOR}" ; exit 1; }
  fi
else
  echo -e "${PREFIX} ${GREEN}initdb -E UTF8 --pgdata ${PGDATA}${ENDCOLOR}"
  su postgres -c "initdb -E UTF8 --pgdata=${PGDATA}"
  STATUS=$?
  if [ $STATUS -ne 0 ]; then
    echo -e "${PREFIX} ${RED} failed to initialize the database${ENDCOLOR}"
  fi
  if [ -d /etc/postgresql ]; then
    echo -e "${PREFIX} ${GREEN}cp -a /etc/postgresql/. ${PGDATA}/ ${ENDCOLOR}"
    cp -a /etc/postgresql/. ${PGDATA}/
  fi
fi
