ARG FROM_TAG="latest"
FROM pulp/pulp-ci-centos:${FROM_TAG}

ARG PULPCORE_VERSION="~=3.21.0"
# These are the final Y versions that support pulpcore 3.21
ARG PULP_ANSIBLE_VERSION="~=0.16.0"
ARG PULP_CERTGUARD_VERSION="~=1.6.0"
ARG PULP_CONTAINER_VERSION="~=2.14.0"
ARG PULP_DEB_VERSION="~=2.20.0"
ARG PULP_FILE_VERSION="~=1.11.0"
ARG PULP_MAVEN_VERSION="~=0.3.0"
ARG PULP_PYTHON_VERSION="~=3.7.0"
ARG PULP_RPM_VERSION="~=3.19.0"

RUN pip3 install --upgrade \
  pulpcore${PULPCORE_VERSION} \
  pulp-ansible${PULP_ANSIBLE_VERSION} \
  pulp-certguard${PULP_CERTGUARD_VERSION} \
  pulp-container${PULP_CONTAINER_VERSION} \
  pulp-deb${PULP_DEB_VERSION} \
  pulp-file${PULP_FILE_VERSION} \
  pulp-maven${PULP_MAVEN_VERSION} \
  pulp-python${PULP_PYTHON_VERSION} \
  pulp-rpm${PULP_RPM_VERSION} \
  requests && \
  rm -rf /root/.cache/pip

RUN ln /usr/local/lib/python3.8/site-packages/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf
RUN ln /usr/local/lib/python3.8/site-packages/pulp_container/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_container.conf
RUN ln /usr/local/lib/python3.8/site-packages/pulp_python/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_python.conf
