ARG FROM_TAG="latest"
FROM pulp/pulp-ci-centos9:${FROM_TAG}

ARG GALAXY_NG_VERSION=""

RUN pip3 install --upgrade \
  git+https://github.com/ansible/galaxy_ng.git@master \
  requests \
  -c /constraints.txt && \
  rm -rf /root/.cache/pip

USER pulp:pulp
RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
       /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
USER root:root

RUN ln $(pip3 show pulp_ansible | sed -n -e 's/Location: //p')/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf
RUN ln $(pip3 show pulp_container | sed -n -e 's/Location: //p')/pulp_container/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_container.conf
RUN ln $(pip3 show galaxy_ng | sed -n -e 's/Location: //p')/galaxy_ng/app/webserver_snippets/nginx.conf /etc/nginx/pulp/galaxy_ng.conf

# allow configuration via env variables
ENV S6_KEEP_ENV=1
COPY images/galaxy/settings.py /etc/pulp/settings.py
