ARG FROM_TAG="latest"
FROM pulp/pulp-ci-centos:${FROM_TAG}

ARG GALAXY_NG_VERSION=""
# Additional debuginfod arguments such as -d DATABASE or -t SECONDS. See man debuginfod for the full argument list
ARG DEBUGINFOD_OPTIONS=""
ENV DEBUGINFOD_ENV=$DEBUGINFOD_OPTIONS

RUN pip3 install --upgrade \
  requests \
  galaxy-ng${GALAXY_NG_VERSION}

RUN ln /usr/local/lib/python3.8/site-packages/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf
RUN ln /usr/local/lib/python3.8/site-packages/pulp_container/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_container.conf
RUN ln /usr/local/lib/python3.8/site-packages/galaxy_ng/app/webserver_snippets/nginx.conf /etc/nginx/pulp/galaxy_ng.conf
