#!/usr/bin/execlineb -S0
foreground {
  /database/assets/wait_on_database_migrations.sh
}
foreground {
  export DJANGO_SETTINGS_MODULE pulpcore.app.settings
  export PULP_CONTENT_ORIGIN localhost
  /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
}
export DJANGO_SETTINGS_MODULE pulpcore.app.settings
export PULP_SETTINGS /etc/pulp/settings.py
/usr/local/bin/gunicorn pulpcore.app.wsgi:application --bind "127.0.0.1:24817" --access-logfile -
