ARG FROM_TAG="latest"
# The multiprocess pulp image must inherit from pulp/pulp-ci-centos9
# The tags follow pulpcore-versioning 3.Y(.Z), we recommend using "latest"
# This image assumes you are using docker/podman run and are using the all-in-one container image to run pulp
# Example of how to enable FIPS in a container - https://repo1.dso.mil/dsop/redhat/ubi/ubi8-fips
FROM pulp/pulp-ci-centos9:${FROM_TAG}

COPY pulp-fips/scripts /scripts
COPY pulp-fips/nssdb/pkcs11.txt /tmp/pkcs11.txt
COPY pulp-fips/requirements.extra.txt /requirements.extra.txt

RUN pip3 install --upgrade \
  -r requirements.extra.txt 

RUN mkdir -p /etc/pki/nssdb && \
    cat /tmp/pkcs11.txt >> /etc/pki/nssdb/pkcs11.txt && \
    chown -R root:root /etc/pki/nssdb && \
    chmod 644 /etc/pki/nssdb/* && \
    dnf clean all && \
    rm -rf /var/cache/dnf /scripts /tmp/pkcs11.txt

