FROM quay.io/pulp/base:latest

RUN pip install git+https://github.com/ansible/galaxy_ng

RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
    /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link && \
    chown -R 700 /var/lib/operator/static/
