ARG FROM_TAG="latest"
FROM pulp/pulp-ci-centos:${FROM_TAG}

ARG PULPCORE_VERSION=""
ARG PULP_ANSIBLE_VERSION=""
ARG PULP_CERTGUARD_VERSION=""
ARG PULP_CONTAINER_VERSION=""
ARG PULP_DEB_VERSION=""
ARG PULP_FILE_VERSION=""
ARG PULP_MAVEN_VERSION=""
ARG PULP_PYTHON_VERSION=""
ARG PULP_RPM_VERSION=""

RUN pip3 install --upgrade \
  pulpcore${PULPCORE_VERSION} \
  pulp-ansible${PULP_ANSIBLE_VERSION} \
  pulp-certguard${PULP_CERTGUARD_VERSION} \
  pulp-container${PULP_CONTAINER_VERSION} \
  pulp-deb${PULP_DEB_VERSION} \
  pulp-file${PULP_FILE_VERSION} \
  pulp-maven${PULP_MAVEN_VERSION} \
  pulp-python${PULP_PYTHON_VERSION} \
  pulp-rpm${PULP_RPM_VERSION} \
  requests && \
  rm -rf /root/.cache/pip

USER pulp:pulp
RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
       /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
USER root:root

RUN ln /usr/local/lib/python3.8/site-packages/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf
RUN ln /usr/local/lib/python3.8/site-packages/pulp_container/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_container.conf
RUN ln /usr/local/lib/python3.8/site-packages/pulp_python/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_python.conf
