FROM quay.io/pulp/base:3.21

RUN pip install galaxy_ng~=4.6.0

USER pulp:pulp
RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
    /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
USER root:root

RUN chmod 2775 /var/lib/pulp/{scripts,media,tmp,assets}
RUN chown -R :root /var/lib/pulp/{scripts,media,tmp,assets} /var/lib/operator/static
