ARG FROM_TAG="latest"
FROM pulp/pulp-ci-centos10:${FROM_TAG}

ARG PULPCORE_VERSION=""
ARG PULP_ANSIBLE_VERSION=""
ARG PULP_CERTGUARD_VERSION=""
ARG PULP_CONTAINER_VERSION=""
ARG PULP_DEB_VERSION=""
ARG PULP_FILE_VERSION=""
ARG PULP_MAVEN_VERSION=""
ARG PULP_PYTHON_VERSION=""
ARG PULP_RPM_VERSION=""
ARG PULP_OSTREE_VERSION=""
ARG PULP_NPM_VERSION=""
ARG PULP_CLI_VERSION=""
# Additional debuginfod arguments such as -d DATABASE or -t SECONDS. See man debuginfod for the full argument list
ARG DEBUGINFOD_OPTIONS=""

RUN uv pip install --upgrade \
  pulpcore${PULPCORE_VERSION} \
  pulp-ansible${PULP_ANSIBLE_VERSION} \
  pulp-certguard${PULP_CERTGUARD_VERSION} \
  pulp-container${PULP_CONTAINER_VERSION} \
  pulp-deb${PULP_DEB_VERSION} \
  pulp-file${PULP_FILE_VERSION} \
  pulp-maven${PULP_MAVEN_VERSION} \
  pulp-python${PULP_PYTHON_VERSION} \
  pulp-rpm${PULP_RPM_VERSION} \
  pulp-ostree${PULP_OSTREE_VERSION} \
  pulp-npm${PULP_NPM_VERSION} \
  pulp-cli${PULP_CLI_VERSION} \
  requests && \
  rm -rf /root/.cache/uv

RUN ln $(pip show pulp_ansible | sed -n -e 's/Location: //p')/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf \
  && ln $(pip show pulp_container | sed -n -e 's/Location: //p')/pulp_container/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_container.conf \
  && ln $(pip show pulp_python | sed -n -e 's/Location: //p')/pulp_python/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_python.conf

# Install debuginfod and run as a background process
RUN dnf -y install elfutils-debuginfod
# You cannot start background processes in a Dockerfile directly (everything is stopped at the end of each RUN command)
# So start debuginfod in a shell script before continuing the default starting script
RUN echo '#!/bin/bash' > start_script.sh
RUN echo "debuginfod -R /var/lib/pulp -Z=cat $DEBUGINFOD_OPTIONS & /init" >> start_script.sh
RUN chmod +x start_script.sh
ENTRYPOINT ["./start_script.sh"]
