name: pulp-oci-images CI

on:
  pull_request:
    paths:
      - "images/**"
      - ".github/**"
      - ".ci/**"
env:
  COLORTERM: 'yes'
  TERM: 'xterm-256color'
  PYTEST_ADDOPTS: '--color=yes'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docs:
    # The workflow tag and the pulpdocs_ref must match.
    uses: "pulp/pulp-docs/.github/workflows/docs-ci.yml@main"
    with:
      pulpdocs_ref: "main"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Check commit message
        env:
          GITHUB_CONTEXT: ${{ github.event.pull_request.commits_url }}
        run: |
          echo ::group::REQUESTS
          pip install pygithub
          echo ::endgroup::
          for sha in $(curl $GITHUB_CONTEXT | jq '.[].sha' | sed 's/"//g')
          do
            python .ci/scripts/validate_commit_message.py $sha
            VALUE=$?
            if [ "$VALUE" -gt 0 ]; then
              exit $VALUE
            fi
          done
        shell: bash

  build-and-test-images:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Build base images
        id: build_base_images
        uses: "./.github/actions/base_images"

      - name: Build pulp-minimal image
        id: build_pulp_minimal_image
        uses: "./.github/actions/build_image"
        with:
          image_name: "pulp-minimal"
          image_variant: "stable"
          latest_ui: ${{ github.base_ref == 'latest' }}
          rebuilt_base_images: ${{ steps.build_base_images.outputs.rebuilt_images }}

      - name: Build pulp image
        id: build_pulp_image
        uses: "./.github/actions/build_image"
        with:
          image_name: "pulp"
          image_variant: "stable"
          latest_ui: ${{ github.base_ref == 'latest' }}
          rebuilt_base_images: ${{ steps.build_base_images.outputs.rebuilt_images }}

      - name: Test pulp-minimal image
        uses: "./.github/actions/test_image"
        with:
          image_name: "pulp-minimal"
          app_branch: ${{ steps.build_pulp_minimal_image.outputs.app_branch }}

      - name: Test pulp image
        uses: "./.github/actions/test_image"
        with:
          image_name: "pulp"
          app_branch: ${{ steps.build_pulp_image.outputs.app_branch }}

      - name: Logs
        if: always()
        run: |
          set +e
          podman ps -a
          podman images -a
          podman logs pulp
          cd images/compose
          podman-compose logs
          podman logs --tail=10000 compose_pulp_api_1
          podman logs --tail=10000 compose_pulp_content_1
          podman logs --tail=10000 compose_pulp_worker_1
          podman logs --tail=10000 compose_pulp_worker_2
          podman logs --tail=10000 compose_pulp_web_1
          VOLUME_PATH=$(podman volume inspect pulpdev | jq -r .[].Mountpoint)
          sudo ls -al $VOLUME_PATH
          sudo tree $VOLUME_PATH
          http --follow --timeout 30 --check-status --pretty format --print hb http://localhost:8080/pulp/api/v3/status/ || true

