# Builds and publishes Pulp images
# Ran nightly performing latest, nightly, & supported version releases
# Can be ran manually with specifying Python version for images to be built with
---
name: Release Image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - latest

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  supported-versions:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # by default, it uses a depth of 1
          # this fetches all history so that we can read each commit
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Set up oras
        uses: oras-project/setup-oras@v1

      - name: Update to the latest pip
        run: python -m pip install --upgrade pip

      - name: Dispatch workflows on stable branches
        run: |
          echo ::group::PYDEPS
          pip install gitpython requests packaging jinja2 pyyaml
          echo ::endgroup::
          if [[ $(date +%u) -eq 7 ]]; then
            # Run CI for all branches on Sunday
            python .ci/scripts/release_ci_branches.py
          else
            python .ci/scripts/release_ci_branches.py --optimize
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  base:
    runs-on: ubuntu-latest
    outputs:
      image_variants: ${{ steps.image_variants.outputs.image_variants }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install python deps
        run: |
          echo ::group::PYDEPS
          pip install requests packaging
          echo ::endgroup::

      # We do not want to build nightly images unless it's a PR to the latest branch,
      # or a branch/dispatch build on the latest branch.
      - name: Set the list of image_variants for later jobs
        id: image_variants
        run: |
          if [ "${{ github.base_ref }}" == "latest" ] || [ "${{ github.ref_name }}" == "latest" ]; then
            if [ "${{ github.event_name }}" == "schedule" ]; then
              echo "image_variants=[\"nightly\",\"stable\"]" >> "$GITHUB_OUTPUT"
            else
              echo "image_variants=[\"stable\"]" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "image_variants=[\"stable\"]" >> "$GITHUB_OUTPUT"
          fi

  build-and-test-images:
    needs: base
    continue-on-error: ${{ matrix.image_variant == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        image_variant: ${{ fromJSON(needs.base.outputs.image_variants) }}
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    outputs:
      # repo_digests format: [
      #   rebuilt-base-images bool, rebuilt-minimal-images bool, rebuilt-pulp-image bool
      #   base sha, pulp-ci-centos9 sha, pulp-minimal sha, pulp-web sha, pulp sha,
      # ]
      stable_arm: ${{ steps.repo_digests.outputs.stable_arm }}
      stable_amd: ${{ steps.repo_digests.outputs.stable_amd }}
      nightly_arm: ${{ steps.repo_digests.outputs.nightly_arm }}
      nightly_amd: ${{ steps.repo_digests.outputs.nightly_amd }}
      stable_app_version: ${{ steps.app_version.outputs.stable_app_version }}
      nightly_app_version: ${{ steps.app_version.outputs.nightly_app_version }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Build base images
        id: build_base_images
        uses: "./.github/actions/base_images"
        with:
          image_variants: ${{ matrix.image_variant }}

      - name: Build pulp-minimal image
        id: build_pulp_minimal_image
        uses: "./.github/actions/build_image"
        with:
          image_name: "pulp-minimal"
          image_variant: ${{ matrix.image_variant }}
          latest_ui: ${{ github.base_ref == 'latest' }}
          rebuilt_base_images: ${{ steps.build_base_images.outputs.rebuilt_images }}

      - name: Build pulp image
        id: build_pulp_image
        uses: "./.github/actions/build_image"
        with:
          image_name: "pulp"
          image_variant: ${{ matrix.image_variant }}
          latest_ui: ${{ github.base_ref == 'latest' }}
          rebuilt_base_images: ${{ steps.build_base_images.outputs.rebuilt_images }}
      
      - name: Set app version
        id: app_version
        run: |
          echo "${{ matrix.image_variant }}_app_version=${{ steps.build_pulp_image.outputs.app_version }}" >> $GITHUB_OUTPUT

      - name: Test pulp-minimal image
        if: ${{ matrix.image_variant != 'nightly' && steps.build_pulp_minimal_image.outputs.rebuilt_images == 'true' }}
        uses: "./.github/actions/test_image"
        with:
          image_name: "pulp-minimal"
          app_branch: ${{ steps.build_pulp_minimal_image.outputs.app_branch }}

      - name: Test pulp image
        if: ${{ matrix.image_variant != 'nightly' && steps.build_pulp_image.outputs.rebuilt_images == 'true' }}
        uses: "./.github/actions/test_image"
        with:
          image_name: "pulp"
          app_branch: ${{ steps.build_pulp_image.outputs.app_branch }}

      # We are doing a temporary upload of the arm or amd images to ghcr.io for the next job to use
      - name: Login to ghcr.io
        env:
          PULP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULP_GITHUB_USERNAME: ${{ github.actor }}
        run: echo "$PULP_GITHUB_TOKEN" | podman login -u "$PULP_GITHUB_USERNAME" --password-stdin ghcr.io

      - name: Set tags for temp upload
        run: |
          if [[ "${{ runner.arch }}" == "ARM64" ]]; then
            ARCH="arm"
          else
            ARCH="amd"
          fi
          if [[ ${{ matrix.image_variant }} == "stable" ]]; then
            TAG="${{ steps.app_version.outputs.stable_app_version }}-$ARCH"
          else
            TAG="nightly-$ARCH"
          fi
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "ARCH=${ARCH}" >> $GITHUB_ENV

      - name: Temp upload images to ghcr.io
        run: |
          branch=${{ github.base_ref || github.ref_name }}
          if [[ ${{ steps.build_base_images.outputs.rebuilt_images }} == "true" ]]; then
            podman push pulp/base:ci ghcr.io/pulp/base:${TAG}
            podman push pulp/pulp-ci-centos9:ci ghcr.io/pulp/pulp-ci-centos9:${TAG}
            image_names="ghcr.io/pulp/base:${TAG} ghcr.io/pulp/pulp-ci-centos9:${TAG}"
          else
            image_names="ghcr.io/pulp/base:${branch} ghcr.io/pulp/pulp-ci-centos9:${branch}"
          fi
          if [[ ${{ steps.build_pulp_minimal_image.outputs.rebuilt_images }} == "true" ]]; then
            podman push pulp/pulp-minimal:ci ghcr.io/pulp/pulp-minimal:${TAG}
            podman push pulp/pulp-web:ci ghcr.io/pulp/pulp-web:${TAG}
            image_names="${image_names} ghcr.io/pulp/pulp-minimal:${TAG} ghcr.io/pulp/pulp-web:${TAG}"
          else
            image_names="${image_names} ghcr.io/pulp/pulp-minimal:${branch} ghcr.io/pulp/pulp-web:${branch}"
          fi
          if [[ ${{ steps.build_pulp_image.outputs.rebuilt_images }} == "true" ]]; then
            podman push pulp/pulp:ci ghcr.io/pulp/pulp:${TAG}
            image_names="${image_names} ghcr.io/pulp/pulp:${TAG}"
          else
            image_names="${image_names} ghcr.io/pulp/pulp:${branch}"
          fi
          echo "Image names: ${image_names}"
          echo "image_names=${image_names}" >> $GITHUB_ENV

      - name: Set output of repo digests of uploaded images
        id: repo_digests
        run: |
          repo_digests="${{ steps.build_base_images.outputs.rebuilt_images }}"
          repo_digests="${repo_digests} ${{ steps.build_pulp_minimal_image.outputs.rebuilt_images }}"
          repo_digests="${repo_digests} ${{ steps.build_pulp_image.outputs.rebuilt_images }}"
          for img in ${image_names}; do
            # This takes advantage of the fact that skopeo will choose the correct platform for the image
            repo_digests="${repo_digests} $(skopeo inspect --format='{{ .Digest }}' docker://${img} )"
          done
          echo "Repo digests: ${repo_digests}"
          echo "${{ matrix.image_variant }}_${ARCH}=${repo_digests}" >> $GITHUB_OUTPUT

      - name: Logs
        if: always()
        run: |
          set +e
          podman ps -a
          podman images -a
          podman logs pulp
          cd images/compose
          podman-compose logs
          podman logs --tail=10000 compose_pulp_api_1
          podman logs --tail=10000 compose_pulp_content_1
          podman logs --tail=10000 compose_pulp_worker_1
          podman logs --tail=10000 compose_pulp_worker_2
          podman logs --tail=10000 compose_pulp_web_1
          VOLUME_PATH=$(podman volume inspect pulpdev | jq -r .[].Mountpoint)
          sudo ls -al $VOLUME_PATH
          sudo tree $VOLUME_PATH
          http --follow --timeout 30 --check-status --pretty format --print hb http://localhost:8080/pulp/api/v3/status/ || true

  publish-images:
    needs: [base,build-and-test-images]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_variant: ${{ fromJSON(needs.base.outputs.image_variants) }}
    steps:
      - uses: actions/checkout@v4

      # Nightly is allowed to fail the build step, so check if we need to publish
      - name: Check nightly passed
        if: ${{ matrix.image_variant == 'nightly' }}
        run: |
          arm=(${{ needs.build-and-test-images.outputs.nightly_arm }})
          amd=(${{ needs.build-and-test-images.outputs.nightly_amd }})
          if [[ ${#arm[@]} -ne 8 || ${#amd[@]} -ne 8 ]]; then
            echo "Nightly build failed, check previous steps"
            echo "arm digests: ${arm[@]}"
            echo "amd digests: ${amd[@]}"
            exit 1
          fi

      # Merging the arm & amd images together and determining if they need to be published
      - name: Get previous output
        run: |
          repo_digests_arm=(${{ needs.build-and-test-images.outputs[format('{0}_arm', matrix.image_variant)] }})
          repo_digests_amd=(${{ needs.build-and-test-images.outputs[format('{0}_amd', matrix.image_variant)] }})
          rebuilt_base_images="${repo_digests_arm[0]} ${repo_digests_amd[0]}"
          rebuilt_minimal_images="${repo_digests_arm[1]} ${repo_digests_amd[1]}"
          rebuilt_pulp_image="${repo_digests_arm[2]} ${repo_digests_amd[2]}"
          base_digests="${repo_digests_arm[3]} ${repo_digests_amd[3]}"
          pulp_ci_centos9_digests="${repo_digests_arm[4]} ${repo_digests_amd[4]}"
          pulp_minimal_digests="${repo_digests_arm[5]} ${repo_digests_amd[5]}"
          pulp_web_digests="${repo_digests_arm[6]} ${repo_digests_amd[6]}"
          pulp_digests="${repo_digests_arm[7]} ${repo_digests_amd[7]}"
          echo "rebuilt_base_images=${rebuilt_base_images}" >> $GITHUB_ENV
          echo "rebuilt_minimal_images=${rebuilt_minimal_images}" >> $GITHUB_ENV
          echo "rebuilt_pulp_image=${rebuilt_pulp_image}" >> $GITHUB_ENV
          echo "base_digests=${base_digests}" >> $GITHUB_ENV
          echo "pulp_ci_centos9_digests=${pulp_ci_centos9_digests}" >> $GITHUB_ENV
          echo "pulp_minimal_digests=${pulp_minimal_digests}" >> $GITHUB_ENV
          echo "pulp_web_digests=${pulp_web_digests}" >> $GITHUB_ENV
          echo "pulp_digests=${pulp_digests}" >> $GITHUB_ENV

      - name: Pull images if needed
        run: |
          if [[ ${{ contains(env.rebuilt_base_images, 'true') }} == 'true' ]]; then
            base_digests=(${{ env.base_digests }})
            pulp_ci_centos9_digests=(${{ env.pulp_ci_centos9_digests }})
            podman pull "ghcr.io/pulp/base@${base_digests[0]}" "ghcr.io/pulp/base@${base_digests[1]}"
            podman tag "ghcr.io/pulp/base@${base_digests[0]}" pulp/base:ci-arm64
            podman tag "ghcr.io/pulp/base@${base_digests[1]}" pulp/base:ci-amd64
            podman pull "ghcr.io/pulp/pulp-ci-centos9@${pulp_ci_centos9_digests[0]}" "ghcr.io/pulp/pulp-ci-centos9@${pulp_ci_centos9_digests[1]}"
            podman tag "ghcr.io/pulp/pulp-ci-centos9@${pulp_ci_centos9_digests[0]}" pulp/pulp-ci-centos9:ci-arm64
            podman tag "ghcr.io/pulp/pulp-ci-centos9@${pulp_ci_centos9_digests[1]}" pulp/pulp-ci-centos9:ci-amd64
            images="base pulp-ci-centos9"
          fi
          if [[ ${{ contains(env.rebuilt_minimal_images, 'true') }} == 'true' ]]; then
            pulp_minimal_digests=(${{ env.pulp_minimal_digests }})
            pulp_web_digests=(${{ env.pulp_web_digests }})
            podman pull "ghcr.io/pulp/pulp-minimal@${pulp_minimal_digests[0]}" "ghcr.io/pulp/pulp-minimal@${pulp_minimal_digests[1]}"
            podman pull "ghcr.io/pulp/pulp-web@${pulp_web_digests[0]}" "ghcr.io/pulp/pulp-web@${pulp_web_digests[1]}"
            podman tag "ghcr.io/pulp/pulp-minimal@${pulp_minimal_digests[0]}" pulp/pulp-minimal:ci-arm64
            podman tag "ghcr.io/pulp/pulp-minimal@${pulp_minimal_digests[1]}" pulp/pulp-minimal:ci-amd64
            podman tag "ghcr.io/pulp/pulp-web@${pulp_web_digests[0]}" pulp/pulp-web:ci-arm64
            podman tag "ghcr.io/pulp/pulp-web@${pulp_web_digests[1]}" pulp/pulp-web:ci-amd64
            images="${images} pulp-minimal pulp-web"
          fi
          if [[ ${{ contains(env.rebuilt_pulp_image, 'true') }} == 'true' ]]; then
            pulp_digests=(${{ env.pulp_digests }})
            podman pull "ghcr.io/pulp/pulp@${pulp_digests[0]}" "ghcr.io/pulp/pulp@${pulp_digests[1]}"
            podman tag "ghcr.io/pulp/pulp@${pulp_digests[0]}" pulp/pulp:ci-arm64
            podman tag "ghcr.io/pulp/pulp@${pulp_digests[1]}" pulp/pulp:ci-amd64
            images="${images} pulp"
          fi
          podman images -a
          echo "Images to publish: $images"
          echo "IMAGES=${images}" >> $GITHUB_ENV

      - name: Set image tags
        run: |
          version="${{ needs.build-and-test-images.outputs[format('{0}_app_version', matrix.image_variant)] }}"
          branch=$(echo ${version} | grep -oP '\d+\.\d+')
          tags="${branch} ${version}"
          if [[ ${{ matrix.image_variant }} == "stable" ]]; then
            if [ "${{ github.ref_name }}" == "latest" ]; then
              tags="${tags} latest stable"
            fi
          else
            tags="${tags} nightly"
          fi
          tags=$(echo "${tags}" | xargs -n1 | sort -u | xargs)
          echo "Set tags to: $tags"
          echo "TAGS=${tags}" >> $GITHUB_ENV

      - name: Publish images
        if: ${{ env.IMAGES }}
        uses: "./.github/actions/publish_images"
        with:
          image_names: ${{ env.IMAGES }}
          tags: ${{ env.TAGS }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_bot_username: ${{ secrets.DOCKER_BOT_USERNAME }}
          docker_bot_password: ${{ secrets.DOCKER_BOT_PASSWORD }}
          quay_bot_username: ${{ secrets.QUAY_BOT_USERNAME }}
          quay_bot_password: ${{ secrets.QUAY_BOT_PASSWORD }}
