ARG FROM_TAG="latest"
FROM pulp/pulp-ci-centos9:${FROM_TAG}

RUN pip3 install --upgrade \
  git+https://github.com/pulp/pulpcore@main \
  git+https://github.com/pulp/pulp_ansible@main \
  git+https://github.com/pulp/pulp-certguard@main \
  git+https://github.com/pulp/pulp_container@main \
  git+https://github.com/pulp/pulp_deb@main \
  git+https://github.com/pulp/pulp_file@main \
  git+https://github.com/pulp/pulp_gem@main \
  git+https://github.com/pulp/pulp_maven@main \
  git+https://github.com/pulp/pulp_ostree@main \
  git+https://github.com/pulp/pulp_python@main \
  git+https://github.com/pulp/pulp_rpm@main \
  rhsm \
  -c /constraints.txt && \
  rm -rf /root/.cache/pip

USER pulp:pulp
RUN PULP_STATIC_ROOT=/var/lib/operator/static/ PULP_CONTENT_ORIGIN=localhost \
       /usr/local/bin/pulpcore-manager collectstatic --clear --noinput --link
USER root:root

RUN ln $(pip3 show pulp_ansible | sed -n -e 's/Location: //p')/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf
RUN ln $(pip3 show pulp_container | sed -n -e 's/Location: //p')/pulp_container/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_container.conf
RUN ln $(pip3 show pulp_python | sed -n -e 's/Location: //p')/pulp_python/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_python.conf
